# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8600f8be6e0761825e206b4dc42e4cf1"
name = "nninja-app-one"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "nninja.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_discounts,read_orders,read_products,write_discounts,write_orders,write_pixels,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://nninja.myshopify.com/apps/ninjastor"
subpath = "ninjastor"
prefix = "apps"

[pos]
embedded = false
